### ISSUE TITLE
Armor Piercing Trait isn´t working in 1.19.2

### ISSUE THREAD

**Issue by alexvirgo13** [ObliviousSpartan/SpartanWeaponry-API#22]
The Armor Piercing trait isn't working in 1.19.2 in any way

Damage done by the netherite warhammer (10dmg)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/48214446/4c8292c0-9a50-442d-8b26-570738035e2f)

Damage done by the netherite axe (10dmg)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/48214446/a0a783e5-088e-49f1-9a3d-4194020aca0b)

I tested 1.18 and it appears to be working just fine
Also, I tested the results on a zombie with armor just to be sure the dummy mod wasn't the issue

**Comment by ObliviousSpartan** [comment]
I figured out what caused this issue, and it turned out that it affected more than just this. It also affected picking up arrows directly from their entity.
It was a typo in my Mixin config which prevented all of my Mixin from working. It also was working properly in my dev environment so I overlooked it.
Oh well, it's fixed now and it will be in the next update. I'll close it when it's live

**Comment by ObliviousSpartan** [comment]
I've updated the mod to fix this.
Closing issue.
