### ISSUE TITLE
incompatibility with REI

### ISSUE THREAD

**Issue by giova-01** [ObliviousSpartan/SpartanWeaponry-API#26]
I want to hide some weapons in REI made with materials that players wont have access to in my modpack, like platinum, but all the throwable weapons can´t be hidden for some reason. I tried with Craftweaker, KubeJS and Item Obliterator but none of them worked.

i think it has something to do with UUIDs, because they are the only type of weapons wich use them, but i dont really know.
![2024-02-23_22 28 47](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/80795034/d106ee66-571c-47e0-9465-5fd8746281b1)

**Comment by giova-01** [comment]
(I am in 1.19.2 Forge) sry

**Comment by ObliviousSpartan** [comment]
I tested this on my end and I'm not sure exactly why it doesn't want to hide these items.
REI must see each weapon with UUIDs as unique (or something like that). Might have to see about making REI ignore UUIDs for them since it's only used for merging ammo together without mixing them up.
I wonder if making an REI plugin for this specific purpose might help.
