### ISSUE TITLE
Doubts about the release for 1.20.1...

### ISSUE THREAD

**Issue by marcos4503** [ObliviousSpartan/SpartanWeaponry-API#31]
Hello!

I understand that developing mods (as well as software) can be very hard work, and sometimes it can be challenging to balance all of this with our personal lives and other tasks... I really wanted to contact you to find out about the possibility of a release of the mod for 1.20.1 and if there is this possibility, how long could it take approximately in months?

I sincerely apologize for contacting you here, but this mod is on my list of the top 5 best mods of my life, and I'm working on a modpack for me to play with friends and family, and your mod is absolutely indispensable!

Forgive me for this inconvenience!

**Comment by ObliviousSpartan** [comment]
Hey,
I've mainly been busy with fixing up a few bugs and integration issues with a few mods in the 1.18.2 and 1.19.2 versions of the mod, and that has caused a delay in the 1.20.1 version being released. That's mainly because the bug fixes will wind up being forward-ported to the 1.20.1 version as well.
That version has also had a few significant changes with the way certain features work while some were expected (like the Smithing Table now having an extra slot for Smithing Templates), others... were not (model loading textures with custom titles, which caused a bug with Oiled weapons being invisible) that caused further delays.
The fixes for the 1.18.2 and 1.19.2 versions will be out within the next few days, so hopefully I can get the 1.20.1 version out after that too.

**Comment by Ezoteric** [comment]
You absolute legend, im still weeks if not months away fixing my modpack so i have all the time but this and your shield mod would be a blessing to have on 1.20.1 as it be the perfect addition for mine and slash :D 
And maybe add a scimitar as we also skinned one of those for purebdcraft :P
