### ISSUE TITLE
Changing Weapon Traits

### ISSUE THREAD

**Issue by loganj2000** [ObliviousSpartan/SpartanWeaponry-API#40]
I'm working on a modpack, and id like maces and both hammers to penetrate armor, and id like most 2 handed weapons to have the parrying daggers block. Is there any way to change the traits? Sorry if this is in the wrong place. Thank you in advance.

**Comment by ObliviousSpartan** [comment]
Which version of Minecraft are you running? Because if you are running 1.18.2 or 1.19.2 (or 1.20.1 soon) it should be possible using a datapack. The 1.16.5 versions and older are hard-coded in so they can't be changed though.

There is a bit to know about changing them though. You'll need to know how to create and enable datapacks and you will need to override the Battle Hammer, Warhammer and Flanged Maces weapon trait tags. Hopefully this guide helps: [https://github.com/ObliviousSpartan/SpartanWeaponry/wiki/Weapon-Trait-Tags](https://github.com/ObliviousSpartan/SpartanWeaponry/wiki/Weapon-Trait-Tags)

If the guide is confusing, let me know and I'll answer any questions you have about how this works.
