### ISSUE TITLE
Unable to change durability of weapons using external sources

### ISSUE THREAD

**Issue by TsEndere** [ObliviousSpartan/SpartanWeaponry-API#45]
this may not be something you can fix, if you cant, its totally understandable. though i believe this is an override created by this mod. this seems to not be in effect for some throwing weapons, which i am able to manually override myself as they do not change durability through the config provided by the mod

the mod i am using is propertymodifier, and it works for everything else. I do not believe the mod matters, as any mod will likely be overridden.

The version is 1.16.5, if that matters at all.

i assume this comes from the config being able to be changed in game though i could be very wrong

weapons not overriding
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/8588dd93-6374-4b11-ac94-8f87f5e83c20)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/15b49f0e-a419-4a74-9fc0-f94c730687e4)

throwing weapons being unsupported by the config and therefore available to be manually overridden (silver longsword for example)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/238db068-faf9-41d6-a177-878022acae9a)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/651173da-94c0-465e-98e5-d54c8e479fbb)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/9b3b1b16-2aa0-4210-bbfb-4ea34c410fd5)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/160214908/c72c6a60-b03e-4f15-9cfd-3428567a0533)

will provide more images if needed, and you may delete this if it is an invalid issue.

**Comment by ObliviousSpartan** [comment]
Actually, the config overriding the durability when loaded is probably why the PropertyModifier mod doesn't work with this, since it probably modifies it earlier. I haven't worked on the 1.16.5 version for a while now so I've forgotten how it works. I believe that I made throwing weapons take the same durability value from the config and divide it by 4 (I think). At least, that's how it works in the newer versions (1.18.2 and above).
Kinda surprised that throwing weapon durabilities can be overridden though. Probably because it doesn't get updated properly when the config value gets changed.
At the very least, you can modify the values using either method, so hopefully it works out well. I still recommend using my config to do this though.
At this stage I don't plan on updating the 1.16.5 version unless a critical bug/crash occurs, so I'll close the issue.
