### ISSUE TITLE
Missing smelting/blasting nugget recipes

### ISSUE THREAD

**Issue by KreloX** [ObliviousSpartan/SpartanWeaponry-API#58]
Weapons should have smelting and blasting recipes for nuggets like vanilla tools for the sake of consistency

**Comment by ObliviousSpartan** [comment]
Yeah this is something I should do. Unfortunately it is more complicated to implement than I thought.
Due to the nature of the mod, there is no guarantee that the nuggets for each of the weapon variants even exists. Additionally, smelting recipes only accept item names as their output rather than tags.
To deal with this, I would need to implement a custom smelting/blasting recipe that accepts tags as a result and a way to disable each recipe when the tag output is empty or weapon input is disabled.

**Comment by ObliviousSpartan** [comment]
I got this working in the version 3.1.2... but... it caused an error that prevented players from entering servers. I also got that fixed.
Additionally, I added some functionality to generate it for datapacks for your addons.
On a somewhat related note, I am taking a look at improving functionality for the API for the next major update, including being able to update damage values on the addon mods side when the config gets updated. Let me know if you have any other suggestions for this.
Closing issue
