### ISSUE TITLE
"No Quiver found!" spam when holding shift with Better Controls installed

### ISSUE THREAD

**Issue by MCRusher** [ObliviousSpartan/SpartanWeaponry-API#63]
Minecraft 1.20.1

Forge 47.3.0

Spartan Weaponry 3.1.1

Better Controls 1.3.0

both mods with default configs

With better controls installed, the game acts as if you are constantly pressing the access quiver keybind (even if the keybind is unset) as long as you hold shift.

If you do have a quiver, it will repeatedly open it while you are trying to sprint.

**Comment by ObliviousSpartan** [comment]
Hi,
I've tested the two mods together and I don't seem to be able to replicate the issue you're having. Is it possible that you've might have changed the quiver keybind for this mod that is causing the spam to happen? (e.g. adding the SHIFT modifier the keybind)
I've labeled this issue as invalid only because I can't replicate the problem. Once I'm able to, I'll remove it.

**Comment by MCRusher** [comment]
I actually unbound the keybind since I was going to just use the inventory.

---

Honestly I can't reproduce it either now.

I recently reinstalled the OS so it's possible that it had an issue with the computer before that a reinstall fixed and I thought it was the game maybe, but I did try toggling off BetterControls and it did stop happening then so idk.

You're probably right, this is likely not a real bug. Sorry about that.

---

Side note, really enjoy your mod, thanks for making it.
