### ISSUE TITLE
Spartan Weaponry/Better Combat/just dual wielding in general Compatibility Issues

### ISSUE THREAD

**Issue by kcobra12** [ObliviousSpartan/SpartanWeaponry-API#71]
Just wanted to bring it to your attention (if you don't already know this) that this mod is incompatible with the Better Combat mod, and requires extra mods to even support dual wielding. Nothing too huge, I just want to dual wield dragonbone sabers.

**Comment by ObliviousSpartan** [comment]
I'm gonna need more information for this...
Which version of the mod are you using?
And which Better Combat mod are you using? There are two different mods with that name now, one for Minecraft 1.12.2 or older, and one for 1.18.2 and higher.
Both versions should have some degree of compatibility with this mod... although since the 1.12.2 version isn't being developed anymore (Better Combat Rebirth, to be clear), there are a few forks which now exist, such as RLCombat, a fork made for RLCraft, which my mod explicitly supports. Other forks aren't compatible sadly.
If you are using the newer Better Combat mod, I added a few datapack files which should add proper compatibility with it, but some features in this mod might not work properly, due to Better Combat taking over how the combat works in totality. If there are any bugs you are experiencing with this version, let me know.

**Comment by v3xed-v0id** [comment]
> If you are using the newer Better Combat mod, I added a few datapack files which should add proper compatibility with it, but some features in this mod might not work properly, due to Better Combat taking over how the combat works in totality. If there are any bugs you are experiencing with this version, let me know.

This mod supports the newer better combat? like [this better combat?](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)

Im gonna have to go test this, i didnt use this mod previously because i assumed it was incompatible due to not listing mod compatibility, ill come back if i find any issues with the mod, thanks for letting me know!
